jobs:
  include:
    - dist: xenial
      arch: ppc64le
    - dist: bionic
      arch: ppc64le
    - dist: focal
      arch: ppc64le

language: python

python:
  - 3.8

sudo: required

script:
  - python --version
  - ls -la $HOME
  - sudo chown -R travis:travis /home/travis/.cargo
  - pip install cryptography==3.4.7
