#jobs:
#  include:
#    - dist: trusty
#      arch: amd64
#    - dist: xenial
#      arch: amd64
#    - dist: bionic
#      arch: amd64
#    - dist: focal
#      arch: amd64
#      #powerjobs
#    - dist: trusty
#      arch: ppc64le
#    - dist: xenial
#      arch: ppc64le
#    - dist: bionic
#      arch: ppc64le
#    - dist: focal
#      arch: ppc64le

langauge: python
arch: 
  - ppc64le
  - amd64
  
dist: focal

python:
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

script:
  - python --version
