jobs:
  include:
    - dist: trusty
      arch: amd64
    - dist: xenial
      arch: amd64
    - dist: bionic
      arch: amd64
    - dist: focal
      arch: amd64
      #powerjobs
    - dist: trusty
      arch: ppc64le
    - dist: xenial
      arch: ppc64le
    - dist: bionic
      arch: ppc64le
    - dist: focal
      arch: ppc64le
  
script:
  - python --version
  - #git config --global --list
  - ls -la /home/travis/.cache
  - ls -la /home/travis/.cache/pip
  - ls -la /home/travis/.cache/pip/wheels
  
